name: dotenv_class_builder
description: "A Flutter package for generating a Dart class from .env variables."

version: 0.1.3
homepage: "https://github.com/RapThorDev/dotenv_class_builder"

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  build_runner: ^2.4.10

flutter:
  plugin:
    platforms:
      pluginClass: DotenvClassBuilderPlugin
